name: zifromania
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^5.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  lottie: ^3.3.1
  animated_text_kit: ^4.2.3
  equatable: ^2.0.7
  package_info_plus: ^8.3.0
  http: ^1.1.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  firebase_remote_config: ^5.0.0
  versionarte: ^2.0.0
  easy_localization: ^3.0.7+1
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.2.1
  in_app_purchase_storekit: ^0.3.22+1
  in_app_purchase_android: ^0.4.0+1
  flutter_secure_storage: ^9.2.4
  webview_flutter: ^4.11.0
  vibration: ^3.1.3
  bloc: ^9.0.0
  get_it: ^8.0.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  share_plus: ^11.0.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    -  assets/sounds/
    -  assets/images/
    -  assets/icons/
    -  assets/lotties/timer.json
    -  assets/translations/
    -  assets/html/


  fonts:
    - family: Onacona
      fonts:
        - asset: assets/fonts/Onacona.ttf
    - family: Brawler
      fonts:
        - asset: assets/fonts/Brawler.ttf
          weight: 700
    - family: rimouskisb
      fonts:
        - asset: assets/fonts/rimouskisb.otf
    - family: WAGHU-PersonalUse
      fonts:
        - asset: assets/fonts/WAGHU-PersonalUse.otf
    - family: Scabber
      fonts:
        - asset: assets/fonts/Scabber.ttf
